### ISSUE TITLE
I use the atcom in my raspberrypi. But 'qiopen' is not work..

### ISSUE THREAD

**Issue by AustinHyun** [sixfab/atcom#14]
In my computer
-----------------------------------------------------
AT+QIACT=1
->OK
AT+QIOPEN=1,0,"TCP","110.165.17.3",9091,0,2
->CONNECT
-----------------------------------------------------
is success. 

But fail NO.2 in my raspberry pi4 bash.
-----------------------------------------------------
atcom AT+QIACT=1
->OK
atcom AT+QIOPEN=1,0,"TCP","110.165.17.3",9091,0,2
->ERROR
-----------------------------------------------------
what am i wrong?

-----------------------------------------------------
atcom AT+QIGETERROR
->+QIGETERROR: 552,invalid parameters
OK
-----------------------------------------------------
i guess i use same parameters..

**Comment by saeedjohar** [comment]
Please follow the instructions mentioned here. 
https://github.com/sixfab/atcom#warning
