### ISSUE TITLE
atcom cannot connect to Telit modem

### ISSUE THREAD

**Issue by mtbsteve** [sixfab/atcom#19]
I installed atcom as described, however I cannot connect to the Telit modem. Any AT commands result in the same error.
```
pi@raspberrypilte:~ $ atcom --port /dev/ttyUSB2 -b 115200 AT
[ERR]   Couldn't open serial communication
pi@raspberrypilte:~ $ 
```
If I run the connection via minicom `minicom -D /dev/ttyUSB2 -b 115200` , everything works.

RasperryPI Bullseye, Python 3.9.2 installed.

EDIT:
It found a connection at /dev/ttyUSB3. I accidentially tried USB2 since this is the right port address when I use minicom.
However, the the automatic port scan seems not to work as I always need to add the -p option.

**Comment by selengalp** [comment]
atcom can not open the serial port when this port being already busy. Minicom or another app may be occupied this serial port. You can try to kill process occupying the ttyUSB2 and run atcom again without -p parameter.
